/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotesRouteImport } from './routes/_votes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as VotesVoteRouteImport } from './routes/_votes/vote'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuthRouteImport } from './routes/admin/_auth'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthDashboardRouteImport } from './routes/admin/_auth/dashboard'
import { Route as AdminAuthUsersRouteImport } from './routes/admin/_auth/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesRoute = VotesRouteImport.update({
  id: '/_votes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesVoteRoute = VotesVoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => VotesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/_auth',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthDashboardRoute = AdminAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAuthRoute,
} as any)
const AdminAuthUsersRoute = AdminAuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vote': typeof VotesVoteRoute
  '/admin': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/users': typeof AdminAuthUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/vote': typeof VotesVoteRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminAuthDashboardRoute
  '/admin/users': typeof AdminAuthUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_votes': typeof VotesRouteWithChildren
  '/login': typeof LoginRoute
  '/_votes/vote': typeof VotesVoteRoute
  '/admin/_auth': typeof AdminAuthRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/_auth/dashboard': typeof AdminAuthDashboardRoute
  '/admin/_auth/users': typeof AdminAuthUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/vote'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/admin/dashboard'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/vote'
    | '/admin'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_votes'
    | '/login'
    | '/_votes/vote'
    | '/admin/_auth'
    | '/admin/login'
    | '/admin/'
    | '/admin/_auth/dashboard'
    | '/admin/_auth/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VotesRoute: typeof VotesRouteWithChildren
  LoginRoute: typeof LoginRoute
  AdminAuthRoute: typeof AdminAuthRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_votes': {
      id: '/_votes'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_votes/vote': {
      id: '/_votes/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VotesVoteRouteImport
      parentRoute: typeof VotesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth': {
      id: '/admin/_auth'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_auth/dashboard': {
      id: '/admin/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAuthDashboardRouteImport
      parentRoute: typeof AdminAuthRoute
    }
    '/admin/_auth/users': {
      id: '/admin/_auth/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAuthUsersRouteImport
      parentRoute: typeof AdminAuthRoute
    }
  }
}

interface VotesRouteChildren {
  VotesVoteRoute: typeof VotesVoteRoute
}

const VotesRouteChildren: VotesRouteChildren = {
  VotesVoteRoute: VotesVoteRoute,
}

const VotesRouteWithChildren = VotesRoute._addFileChildren(VotesRouteChildren)

interface AdminAuthRouteChildren {
  AdminAuthDashboardRoute: typeof AdminAuthDashboardRoute
  AdminAuthUsersRoute: typeof AdminAuthUsersRoute
}

const AdminAuthRouteChildren: AdminAuthRouteChildren = {
  AdminAuthDashboardRoute: AdminAuthDashboardRoute,
  AdminAuthUsersRoute: AdminAuthUsersRoute,
}

const AdminAuthRouteWithChildren = AdminAuthRoute._addFileChildren(
  AdminAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VotesRoute: VotesRouteWithChildren,
  LoginRoute: LoginRoute,
  AdminAuthRoute: AdminAuthRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
